# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Car_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1944, 854)
        self.layout_MainHorizontal = QtWidgets.QHBoxLayout(Form)
        self.layout_MainHorizontal.setObjectName("layout_MainHorizontal")
        self.grp_Inputs = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_Inputs.sizePolicy().hasHeightForWidth())
        self.grp_Inputs.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grp_Inputs.setFont(font)
        self.grp_Inputs.setObjectName("grp_Inputs")
        self.gridLayout = QtWidgets.QGridLayout(self.grp_Inputs)
        self.gridLayout.setObjectName("gridLayout")
        self.le_AngDeg = QtWidgets.QLineEdit(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_AngDeg.sizePolicy().hasHeightForWidth())
        self.le_AngDeg.setSizePolicy(sizePolicy)
        self.le_AngDeg.setMinimumSize(QtCore.QSize(75, 0))
        self.le_AngDeg.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_AngDeg.setFont(font)
        self.le_AngDeg.setObjectName("le_AngDeg")
        self.gridLayout.addWidget(self.le_AngDeg, 6, 1, 1, 1)
        self.le_c1 = QtWidgets.QLineEdit(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_c1.sizePolicy().hasHeightForWidth())
        self.le_c1.setSizePolicy(sizePolicy)
        self.le_c1.setMinimumSize(QtCore.QSize(75, 0))
        self.le_c1.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_c1.setFont(font)
        self.le_c1.setObjectName("le_c1")
        self.gridLayout.addWidget(self.le_c1, 3, 1, 1, 1)
        self.lbl_k2 = QtWidgets.QLabel(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_k2.sizePolicy().hasHeightForWidth())
        self.lbl_k2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_k2.setFont(font)
        self.lbl_k2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_k2.setObjectName("lbl_k2")
        self.gridLayout.addWidget(self.lbl_k2, 5, 0, 1, 1, QtCore.Qt.AlignRight)
        self.lbl_Dashpot = QtWidgets.QLabel(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_Dashpot.sizePolicy().hasHeightForWidth())
        self.lbl_Dashpot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_Dashpot.setFont(font)
        self.lbl_Dashpot.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Dashpot.setObjectName("lbl_Dashpot")
        self.gridLayout.addWidget(self.lbl_Dashpot, 3, 0, 1, 1)
        self.le_CarSpeed = QtWidgets.QLineEdit(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_CarSpeed.sizePolicy().hasHeightForWidth())
        self.le_CarSpeed.setSizePolicy(sizePolicy)
        self.le_CarSpeed.setMinimumSize(QtCore.QSize(75, 0))
        self.le_CarSpeed.setMaximumSize(QtCore.QSize(300, 16777215))
        self.le_CarSpeed.setObjectName("le_CarSpeed")
        self.gridLayout.addWidget(self.le_CarSpeed, 1, 1, 1, 1)
        self.lbl_CarBodyMass = QtWidgets.QLabel(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_CarBodyMass.sizePolicy().hasHeightForWidth())
        self.lbl_CarBodyMass.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_CarBodyMass.setFont(font)
        self.lbl_CarBodyMass.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_CarBodyMass.setObjectName("lbl_CarBodyMass")
        self.gridLayout.addWidget(self.lbl_CarBodyMass, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.lbl_Spring1 = QtWidgets.QLabel(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_Spring1.sizePolicy().hasHeightForWidth())
        self.lbl_Spring1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_Spring1.setFont(font)
        self.lbl_Spring1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Spring1.setObjectName("lbl_Spring1")
        self.gridLayout.addWidget(self.lbl_Spring1, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.lbl_CarSpeed = QtWidgets.QLabel(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_CarSpeed.sizePolicy().hasHeightForWidth())
        self.lbl_CarSpeed.setSizePolicy(sizePolicy)
        self.lbl_CarSpeed.setObjectName("lbl_CarSpeed")
        self.gridLayout.addWidget(self.lbl_CarSpeed, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.lbl_RampANgle = QtWidgets.QLabel(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_RampANgle.sizePolicy().hasHeightForWidth())
        self.lbl_RampANgle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_RampANgle.setFont(font)
        self.lbl_RampANgle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_RampANgle.setObjectName("lbl_RampANgle")
        self.gridLayout.addWidget(self.lbl_RampANgle, 6, 0, 1, 1, QtCore.Qt.AlignRight)
        self.layourhorizontal = QtWidgets.QHBoxLayout()
        self.layourhorizontal.setObjectName("layourhorizontal")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layourhorizontal.addItem(spacerItem)
        self.chk_LogX = QtWidgets.QCheckBox(self.grp_Inputs)
        self.chk_LogX.setObjectName("chk_LogX")
        self.layourhorizontal.addWidget(self.chk_LogX)
        self.chk_LogY = QtWidgets.QCheckBox(self.grp_Inputs)
        self.chk_LogY.setObjectName("chk_LogY")
        self.layourhorizontal.addWidget(self.chk_LogY, 0, QtCore.Qt.AlignRight)
        self.chk_LogAccel = QtWidgets.QCheckBox(self.grp_Inputs)
        self.chk_LogAccel.setObjectName("chk_LogAccel")
        self.layourhorizontal.addWidget(self.chk_LogAccel, 0, QtCore.Qt.AlignRight)
        self.gridLayout.addLayout(self.layourhorizontal, 11, 0, 1, 2)
        self.lbl_m2 = QtWidgets.QLabel(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_m2.sizePolicy().hasHeightForWidth())
        self.lbl_m2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_m2.setFont(font)
        self.lbl_m2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_m2.setObjectName("lbl_m2")
        self.gridLayout.addWidget(self.lbl_m2, 4, 0, 1, 1, QtCore.Qt.AlignRight)
        self.le_k2 = QtWidgets.QLineEdit(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_k2.sizePolicy().hasHeightForWidth())
        self.le_k2.setSizePolicy(sizePolicy)
        self.le_k2.setMinimumSize(QtCore.QSize(75, 0))
        self.le_k2.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_k2.setFont(font)
        self.le_k2.setObjectName("le_k2")
        self.gridLayout.addWidget(self.le_k2, 5, 1, 1, 1)
        self.le_mcar = QtWidgets.QLineEdit(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_mcar.sizePolicy().hasHeightForWidth())
        self.le_mcar.setSizePolicy(sizePolicy)
        self.le_mcar.setMinimumSize(QtCore.QSize(75, 0))
        self.le_mcar.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_mcar.setFont(font)
        self.le_mcar.setObjectName("le_mcar")
        self.gridLayout.addWidget(self.le_mcar, 0, 1, 1, 1)
        self.le_k1 = QtWidgets.QLineEdit(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_k1.sizePolicy().hasHeightForWidth())
        self.le_k1.setSizePolicy(sizePolicy)
        self.le_k1.setMinimumSize(QtCore.QSize(75, 0))
        self.le_k1.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_k1.setFont(font)
        self.le_k1.setObjectName("le_k1")
        self.gridLayout.addWidget(self.le_k1, 2, 1, 1, 1)
        self.le_tMax = QtWidgets.QLineEdit(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_tMax.sizePolicy().hasHeightForWidth())
        self.le_tMax.setSizePolicy(sizePolicy)
        self.le_tMax.setMinimumSize(QtCore.QSize(75, 0))
        self.le_tMax.setMaximumSize(QtCore.QSize(300, 16777215))
        self.le_tMax.setObjectName("le_tMax")
        self.gridLayout.addWidget(self.le_tMax, 7, 1, 1, 1)
        self.le_m2 = QtWidgets.QLineEdit(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_m2.sizePolicy().hasHeightForWidth())
        self.le_m2.setSizePolicy(sizePolicy)
        self.le_m2.setMinimumSize(QtCore.QSize(75, 0))
        self.le_m2.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_m2.setFont(font)
        self.le_m2.setObjectName("le_m2")
        self.gridLayout.addWidget(self.le_m2, 4, 1, 1, 1)
        self.lbl_tMax = QtWidgets.QLabel(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_tMax.sizePolicy().hasHeightForWidth())
        self.lbl_tMax.setSizePolicy(sizePolicy)
        self.lbl_tMax.setObjectName("lbl_tMax")
        self.gridLayout.addWidget(self.lbl_tMax, 7, 0, 1, 1, QtCore.Qt.AlignRight)
        self.chk_IncludeAccel = QtWidgets.QCheckBox(self.grp_Inputs)
        self.chk_IncludeAccel.setObjectName("chk_IncludeAccel")
        self.gridLayout.addWidget(self.chk_IncludeAccel, 13, 0, 1, 2, QtCore.Qt.AlignRight)
        self.lbl_MaxMinInfo = QtWidgets.QLabel(self.grp_Inputs)
        self.lbl_MaxMinInfo.setObjectName("lbl_MaxMinInfo")
        self.gridLayout.addWidget(self.lbl_MaxMinInfo, 15, 0, 1, 2, QtCore.Qt.AlignRight)
        self.chk_PlotAccel = QtWidgets.QCheckBox(self.grp_Inputs)
        self.chk_PlotAccel.setObjectName("chk_PlotAccel")
        self.gridLayout.addWidget(self.chk_PlotAccel, 12, 0, 1, 2, QtCore.Qt.AlignRight)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btn_calculate = QtWidgets.QPushButton(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_calculate.sizePolicy().hasHeightForWidth())
        self.btn_calculate.setSizePolicy(sizePolicy)
        self.btn_calculate.setObjectName("btn_calculate")
        self.horizontalLayout_2.addWidget(self.btn_calculate, 0, QtCore.Qt.AlignRight)
        self.pb_Optimize = QtWidgets.QPushButton(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_Optimize.sizePolicy().hasHeightForWidth())
        self.pb_Optimize.setSizePolicy(sizePolicy)
        self.pb_Optimize.setObjectName("pb_Optimize")
        self.horizontalLayout_2.addWidget(self.pb_Optimize, 0, QtCore.Qt.AlignRight)
        self.gridLayout.addLayout(self.horizontalLayout_2, 8, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 16, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 2, 1, 1)
        self.layout_MainHorizontal.addWidget(self.grp_Inputs, 0, QtCore.Qt.AlignLeft)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.grp_Inputs.setTitle(_translate("Form", "Model Inputs"))
        self.le_AngDeg.setText(_translate("Form", "45"))
        self.le_c1.setText(_translate("Form", "4500"))
        self.lbl_k2.setText(_translate("Form", "Tire spring constant (k2, N/m)"))
        self.lbl_Dashpot.setText(_translate("Form", "Suspension Shock Absorber (c1, N*s/m)"))
        self.le_CarSpeed.setText(_translate("Form", "120"))
        self.lbl_CarBodyMass.setText(_translate("Form", "Car body mass (m1, kg)"))
        self.lbl_Spring1.setText(_translate("Form", "Suspension Spring (k1, N/m)"))
        self.lbl_CarSpeed.setText(_translate("Form", "Car Speed (kph)"))
        self.lbl_RampANgle.setText(_translate("Form", "Ramp Angle (deg)"))
        self.chk_LogX.setText(_translate("Form", "log scale t"))
        self.chk_LogY.setText(_translate("Form", "log scale Y"))
        self.chk_LogAccel.setText(_translate("Form", "log scale Y\'\'"))
        self.lbl_m2.setText(_translate("Form", "Wheel mass (m2, kg)"))
        self.le_k2.setText(_translate("Form", "90000"))
        self.le_mcar.setText(_translate("Form", "450"))
        self.le_k1.setText(_translate("Form", "15000"))
        self.le_tMax.setText(_translate("Form", "3"))
        self.le_m2.setText(_translate("Form", "20"))
        self.lbl_tMax.setText(_translate("Form", "t, max plot (s)"))
        self.chk_IncludeAccel.setText(_translate("Form", "Include Accel in Opt."))
        self.lbl_MaxMinInfo.setText(_translate("Form", "TextLabel"))
        self.chk_PlotAccel.setText(_translate("Form", "Plot Car Accel."))
        self.btn_calculate.setText(_translate("Form", "Calculate"))
        self.pb_Optimize.setText(_translate("Form", "Optimize Suspension"))

